name: Pipeline CI/CD Tela de Login

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci-integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build e Testes Automáticos
      run: |
        echo "Executando Build..."
        echo "Executando Testes de Qualidade no HTML e CSS..." [cite: 582]

  cd-delivery:
    name: Continuous Delivery
    [cite_start]needs: ci-integration 
    runs-on: ubuntu-latest
    steps:
    - name: Preparando Artefatos para Lançamento
      [cite_start]run: echo "Gerando pacote de deploy (Release)..." [cite: 561, 582]